version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_docker-db-1
    restart: always
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: res1234*/
    ports:
      - "3306:3306"
    networks:
      - mysqlNet

  api:
    image: restaurantapi:1.0
    container_name: ApiContainer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql_docker-db-1
      DB_PORT: 3306
      DB_DATABASE: restaurant
      DB_USER: root
      DB_PASSWORD: res1234*/
    networks:
      - mysqlNet

networks:
  mysqlNet:
    driver: bridge
